spring.application.name=ranked-backend
resilience4j.circuitbreaker.instances.startgg.sliding-window-size=5
resilience4j.circuitbreaker.instances.startgg.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.startgg.wait-duration-in-open-state=10s